name = "Indirim Carki"
handle = "indirim-carki"
client_id = "c2a7140be0fb5a9241c8bf1181e0594b"
application_url = "https://ndirimcarkshopify-production.up.railway.app"
embedded = true

[access_scopes]
scopes = "write_discounts,write_customers"

[auth]
redirect_urls = [
  "https://ndirimcarkshopify-production.up.railway.app/auth/callback",
  "https://ndirimcarkshopify-production.up.railway.app/auth/shopify/callback",
  "https://ndirimcarkshopify-production.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[app_proxy]
url = "/proxy"
subpath = "indirim-carki"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
